---
- name: Install prerequisites
  apt:
    name: "{{ apm_server_prereq }}"
    state: present

- name: Add the Elastic APT repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add the Elastic APT repository
  apt_repository:
    repo: "{{ apm_server_elastic_repo_url }}"
    state: present

- name: Install APM Server
  apt:
    name: "apm-server={{ apm_server_version }}"
    state: present

- name: Deploy service configuration
  template:
    src: apm-server.yml.j2
    dest: /etc/apm-server/apm-server.yml
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart apm-server

- name: Ensure the APM service is enabled and started
  service:
    name: apm-server
    state: started
    enabled: yes
